services:
  basket:
    image: redis:alpine

  mongoclient:
    image: mongoclient/mongoclient

  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile

volumes:
  mongo_data:
