services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8888:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    container_name: sqlserver
    restart: always
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Admin@12345"
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin@mail.com
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  mongoclient:
    container_name: mongoclient
    restart: always
    ports:
      - "3000:3000"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:8080"
      - "MessageBrokerSettings:Host=amqp://rabbitmq:5672"
      - "MessageBrokerSettings:Username=guest"
      - "MessageBrokerSettings:Password=guest"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DiscountDbConnection=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin;"
    depends_on:
      - discountdb
    ports:
      - "8002:8080"
      
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DiscountDbConnection=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin;"
    depends_on:
      - discountdb
    ports:
      - "8003:8080"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:OrderingDb=Data Source=sqlserver,1433;Database=OrderDb;User ID=sa;Password=Admin@12345;Encrypt=False;"
      - "EmailSettings:ApiKey=123"
      - "EmailSettings:FromAddress=admin@mail.com"
      - "EmailSettings:FromName=Admin"
      - "MessageBrokerSettings:Host=amqp://rabbitmq:5672"
      - "MessageBrokerSettings:Username=guest"
      - "MessageBrokerSettings:Password=guest"
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "8004:8080"

